# Generated by Django 3.0.3 on 2020-03-15 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0002_auto_20200313_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
    ]
