# Generated by Django 3.0.3 on 2020-02-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0002_auto_20200223_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id']},
        ),
    ]
