# Generated by Django 3.0.2 on 2020-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0002_auto_20200122_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_length_cm',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height_cm',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight_g',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width_cm',
            field=models.CharField(max_length=100),
        ),
    ]
