# Generated by Django 3.0.3 on 2020-02-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0003_auto_20200224_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['?']},
        ),
    ]
