# Generated by Django 3.0.2 on 2020-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0003_auto_20200122_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height_cm',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width_cm',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
