# Generated by Django 3.0.3 on 2020-03-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0004_auto_20200224_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='sales_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='product_id',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
