# Generated by Django 3.0.2 on 2020-01-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0004_auto_20200122_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height_cm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length_cm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight_g',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width_cm',
            field=models.IntegerField(),
        ),
    ]
