# Generated by Django 3.0.2 on 2020-01-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0005_auto_20200122_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_height_cm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length_cm',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight_g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width_cm',
            field=models.FloatField(),
        ),
    ]
