# Generated by Django 3.0.3 on 2020-03-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0005_auto_20200309_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='category_index',
            field=models.FloatField(),
        ),
    ]
