# Generated by Django 3.0.3 on 2020-03-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0006_auto_20200309_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='product_id',
            field=models.OneToOneField(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='RecApp.Product'),
        ),
    ]
