# Generated by Django 3.0.2 on 2020-02-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecApp', '0008_auto_20200205_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
